name: docker-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Show Go Env
        run: go env

      -
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/callback.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: fanchunke/chatgpt-wecom:latest